name: Import to Firebase
on:
  workflow_dispatch:
jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install firebase-admin
      - run: node import_script.js
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
